//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Scheduler.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule
    {
        public int ID { get; set; }
        public string ScheduleText { get; set; }
    }
}
